create table if not exists public.visit_events (
  id bigint generated by default as identity primary key,
  visited_at timestamptz not null default now(),
  country_code text not null default '',
  country text not null default 'Desconhecido',
  region text not null default 'Desconhecido',
  city text not null default 'Desconhecida'
);

alter table public.visit_events enable row level security;

drop policy if exists "Administradores podem consultar visitas" on public.visit_events;
create policy "Administradores podem consultar visitas"
on public.visit_events for select to authenticated
using (exists (select 1 from public.app_admins where app_admins.user_id = auth.uid()));

create or replace function public.record_visit(p_country_code text, p_country text, p_region text, p_city text)
returns void language plpgsql security definer set search_path = public as $$
begin
  insert into public.visit_events (country_code, country, region, city)
  values (
    upper(left(coalesce(p_country_code, ''), 2)),
    left(coalesce(nullif(trim(p_country), ''), 'Desconhecido'), 80),
    left(coalesce(nullif(trim(p_region), ''), 'Desconhecido'), 100),
    left(coalesce(nullif(trim(p_city), ''), 'Desconhecida'), 100)
  );
end;
$$;

revoke all on function public.record_visit(text, text, text, text) from public;
grant execute on function public.record_visit(text, text, text, text) to anon, authenticated;
